apps/empleados/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from apps.empleados.views import EmpleadosCreate,EmpleadosList,EmpleadosDelete,EmpleadosUpdate

urlpatterns = [
    url(r'^$', login_required(EmpleadosList.as_view()), name='empleados_list'),
    url(r'^new$', login_required(EmpleadosCreate.as_view()), name='empleados_new'),
    url(r'^edit/(?P<pk>\d+)$', login_required(EmpleadosUpdate.as_view()), name='empleados_edit'),
    url(r'^delete/(?P<pk>\d+)$', login_required(EmpleadosDelete.as_view()), name='empleados_delete'),
]

crud/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from crud.views import home,Registrar

admin.autodiscover()

urlpatterns = [
    url(r'^login/', 'django.contrib.auth.views.login', {'template_name':'index.html'}, name='login'),
    url(r'^logout/', 'django.contrib.auth.views.logout_then_login', name='logout'),
    url(r'^$', login_required(home), name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^empleados/', include('apps.empleados.urls',namespace='empleados'),name='empleados'),
    url(r'^registrar/$', Registrar, name='registrar'),
    url(r'^reset/password_reset/$', 'django.contrib.auth.views.password_reset',
        {'template_name':'password_reset_form.html','email_template_name': 'password_reset_email.html'}, name='password_reset'),
    url(r'^reset/password_reset/done/$', 'django.contrib.auth.views.password_reset_done',
        {'template_name':'password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm',
        {'template_name':'password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete',
        {'template_name':'password_reset_complete.html'}, name='password_reset_complete'),
]

apps/empleados/models.py
# -*- encoding:UTF-8 -*-
from django.core.validators import RegexValidator
from django.db import models
# Create your models here.

class Direccion(models.Model):
    pais = models.CharField(max_length=30,validators=[
        RegexValidator(
            regex='^[[a-zA-Z]|[ñÑáéíóúÁÉÍÓÚ]]*$',
            message='El país solo debe contener caracteres alfabeticos'
        )
    ])
    estado = models.CharField(max_length=30,validators=[
        RegexValidator(
            regex='^[[a-zA-Z]|[ñÑáéíóúÁÉÍÓÚ]]*$',
            message='El estado solo debe contener caracteres alfabeticos'
        )
    ])
    municipio = models.CharField(max_length=30,validators=[
        RegexValidator(
            regex='^[[a-zA-Z]|[ñÑáéíóúÁÉÍÓÚ]]*$',
            message='El municipio solo debe contener caracteres alfabeticos'
        )
    ])
    ciudad = models.CharField(max_length=40, null=True, blank=True,validators=[
        RegexValidator(
            regex='^[[a-zA-Z]|[ñÑáéíóúÁÉÍÓÚ]]*$',
            message='La ciudad solo debe contener caracteres alfabeticos'
        )
    ])
    calle = models.CharField(max_length=40,validators=[
        RegexValidator(
            regex='^[[0-9a-zA]|[ñÑáéíóúÁÉÍÓÚ°]]*$',
            message='La calle solo debe contener caracteres alfanúmericos'
        )
    ])
    colonia = models.CharField(max_length=30, null=True, blank=True,validators=[
        RegexValidator(
            regex='^[[0-9a-zA]|[ñÑáéíóúÁÉÍÓÚ°]]*$',
            message='La colonia solo debe contener caracteres alfanúmericos'
        )
    ])
    numero_interior = models.CharField(max_length=5, null=True, blank=True,validators=[
        RegexValidator(
            regex='^[[0-9a-zA-Z]|[ñÑ]]*$',
            message='El numero exterior solo debe contener caracteres alfanúmericos'
        )
    ])
    numero_exterior = models.CharField(max_length=5, null=True, blank=True,validators=[
        RegexValidator(
            regex='^[[0-9a-zA-Z]|[ñÑ]]*$',
            message='El numero exterior solo debe contener caracteres alfanúmericos'
        )
    ])
    codigo_postal = models.CharField(max_length=5, null=True, blank=True,validators=[
        RegexValidator(
            regex='^[1-9]{1}[0-9]{4}',
            message='El codigo postal debe tener solo numeros y ademas no iniciar en un cero'
        )
    ])
    datos_adicionales = models.CharField(max_length=120, null=True, blank=True,validators=[
        RegexValidator(
            regex='^[\w]|[ñÑáéíóúÁÉÍÓÚ°]*$',
            message='Los datos adicionales solo debe contener caracteres alfanúmericos'
        )
    ])

    def get_full_information(self):
        return '%s %s %s %s %s %s %s %s %s %s' % (
            self.calle,
            self.numero_interior ,
            self.numero_exterior,
            self.datos_adicionales,
            self.colonia,
            self.municipio,
            self.ciudad,
            self.codigo_postal,
            self.estado,
            self.pais
        )

class Empleado(models.Model):
    fecha_registro= models.DateTimeField(auto_now_add=True)
    activo = models.IntegerField(default=1)
    nombre = models.CharField(max_length=100,validators=[
        RegexValidator(
            regex='^[[a-zA-Z]|[ñÑáéíóúÁÉÍÓÚ]]*$',
            message='El nombre solo debe contener caracteres alfabeticos',
        )
    ])
    apellido_paterno = models.CharField(max_length=50,validators=[
        RegexValidator(
            regex='^[[a-zA-Z]|[ñÑáéíóúÁÉÍÓÚ]]*$',
            message='El apellido paterno solo debe contener caracteres alfabeticos'
        )
    ])
    apellido_materno = models.CharField(max_length=50,null=True,blank=True,validators=[
        RegexValidator(
            regex='^[[a-zA-Z]|[ñÑáéíóúÁÉÍÓÚ]]*$',
            message='El apellido materno solo debe contener caracteres alfabeticos'
        )
    ])
    fecha_de_nacimiento = models.DateField()
    curp = models.CharField(max_length=18,validators=[
        RegexValidator(
            regex='[A-Z]{1}[AEIOU]{1}[A-Z]{2}[0-9]{2}(0[1-9]|1[0-2])(0[1-9]|1[0-9]|2[0-9]|3[0-1])[HM]{1}(AS|BC|BS|CC|CS|CH|CL|CM|DF|DG|GT|GR|HG|JC|MC|MN|MS|NT|NL|OC|PL|QT|QR|SP|SL|SR|TC|TS|TL|VZ|YN|ZS|NE)[B-DF-HJ-NP-TV-Z]{3}[0-9A-Z]{1}[0-9]{1}',
            message='La CURP no tiene el formato requerido'
        )
    ])
    rfc = models.CharField(max_length=14,validators=[
        RegexValidator(
            regex='([A-Z,Ñ,&]{3,4}([0-9]{2})(0[1-9]|1[0-2])(0[1-9]|1[0-9]|2[0-9]|3[0-1])[A-Z|\d]{3,4})',
            message='El RFC no tiene el formato requerido'
        )
    ])
    direccion = models.ForeignKey(Direccion, null=True, blank=True)#, on_delete=models.CASCADE)

    def get_estatus_display(self):
        if self.activo==1:
            return "Activo"
        else:
            return "Inactivo"

    def __unicode__(self):
        return (self.nombre)

apps/empleados/forms.py
# -*- encoding:UTF-8 -*-
import re
from django import forms
from datetime import date, timedelta

from models import Empleado,Direccion

class EmpleadoForm(forms.ModelForm):
    class Meta:
        model = Empleado
        fields = [
            'nombre',
            'apellido_paterno',
            'apellido_materno',
            'fecha_de_nacimiento',
            'curp',
            'rfc',
            'direccion',
        ]
        labels = {
            'apellido_paterno': 'Apellido Paterno',
            'apellido_materno': 'Apellido Materno',
            'fecha_de_nacimiento': 'Fecha de Nacimiento',
            'curp': 'CURP',
            'rfc': 'RFC',
        }
        widgets = {
            "nombre": forms.TextInput(attrs={'placeholder': 'Nombre','class': 'col-md-4 form-control'}),
            "apellido_paterno": forms.TextInput(attrs={'placeholder': 'Apellido Paterno','class': 'col-md-4 form-control'}),
            "apellido_materno": forms.TextInput(attrs={'placeholder': 'Apellido Materno','class': 'col-md-4 form-control'}),
            "fecha_de_nacimiento": forms.DateInput(attrs={'placeholder': 'aaaa-mm-dd','type': 'text', 'id': 'datepicker', 'maxlength': '10','class': 'col-md-4 form-control'}),
            "curp": forms.TextInput(attrs={'placeholder': 'CURP','class': 'col-md-4 form-control'}),
            "rfc": forms.TextInput(attrs={'placeholder': 'RFC','class': 'col-md-4 form-control'}),
            'direccion': forms.HiddenInput(),
        }

    def clean_fecha_de_nacimiento(self):
        diccionario_limpio = self.cleaned_data
        fecha_de_nacimiento = diccionario_limpio.get('fecha_de_nacimiento')
        #Obtenemos la fecha actual y le restamos 18 años
        fecha_actual = date.today() - timedelta(days=6570)
        patron = re.compile('[\d]{4}[-]{1}[\d]{2}[-]{1}[\d]{2}')
        if not patron.match(str(fecha_de_nacimiento)):
            raise forms.ValidationError("La fecha no coincide con el formato requerido")
        elif fecha_actual < fecha_de_nacimiento:
        #if fecha_actual < fecha_de_nacimiento:
            raise forms.ValidationError("El fecha no debe ser mayor al dia de hoy y debe ser de al menos hace 18 años")
        else:
            return fecha_de_nacimiento

class DireccionForm(forms.ModelForm):
    class Meta:
        model = Direccion
        fields = [
            'pais',
            'estado',
            'municipio',
            'ciudad',
            'calle',
            'colonia',
            'numero_interior',
            'numero_exterior',
            'codigo_postal',
            'datos_adicionales',
        ]
        labels = {
            'pais': 'Pais',
            'estado': 'Estado',
            'municipio': 'Municipio',
            'ciudad': 'Ciudad',
            'calle': 'Calle',
            'colonia': 'Colonia',
            'numero_interior': 'Num. Int',
            'numero_exterior': 'Num. Ext',
            'codigo_postal': 'Codigo Postal',
            'datos_adicionales': 'Datos adicionales',
        }
        widgets = {
            "pais": forms.TextInput(attrs={'placeholder': 'Pais','class': 'col-md-4 form-control'}),
            "estado": forms.TextInput(attrs={'placeholder': 'Estado','class': 'col-md-4 form-control'}),
            "municipio": forms.TextInput(attrs={'placeholder': 'Municipio','class': 'col-md-4 form-control'}),
            "ciudad": forms.TextInput(attrs={'placeholder': 'Ciudad','class': 'col-md-4 form-control'}),
            "calle": forms.TextInput(attrs={'placeholder': 'Calle','class': 'col-md-4 form-control'}),
            "colonia": forms.TextInput(attrs={'placeholder': 'Colonia','class': 'col-md-4 form-control'}),
            "numero_interior": forms.TextInput(attrs={'placeholder': 'Num. Int','class': 'col-md-4 form-control'}),
            "numero_exterior": forms.TextInput(attrs={'placeholder': 'Num. Ext','class': 'col-md-4 form-control'}),
            "codigo_postal": forms.TextInput(attrs={'placeholder': 'Codigo Postal','class': 'col-md-4 form-control'}),
            "datos_adicionales": forms.TextInput(attrs={'placeholder': 'Datos adicionales','class': 'col-md-4 form-control'}),
        }

apps/empleados/views.py
from django.core.urlresolvers import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from apps.empleados.models import Empleado,Direccion
from apps.empleados.forms import EmpleadoForm,DireccionForm
# Create your views here.

class EmpleadosList(ListView):
    model = Empleado
    second_model = Direccion

    def get_queryset(self):
        queryset = self.model.objects.filter(activo=1).order_by('id')
        return queryset

class EmpleadosCreate(CreateView):
    model = Empleado
    form_class = EmpleadoForm
    second_form_class = DireccionForm
    success_url = reverse_lazy('empleados:empleados_list')

    def get_context_data(self, **kwargs):
        context = super(EmpleadosCreate, self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class(self.request.GET)
        if 'form2' not in context:
            context['form2'] = self.second_form_class(self.request.GET)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        form = self.form_class(request.POST)
        form2 = self.second_form_class(request.POST)
        if form.is_valid() and form2.is_valid():
            usuario = form.save(commit=False)
            #direccion = form2.save(commit=False)
            usuario.direccion = form2.save()
            usuario.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.render_to_response(
              self.get_context_data(form=form, form2=form2))

class EmpleadosUpdate(UpdateView):
    model = Empleado
    form_class = EmpleadoForm
    second_form_class = DireccionForm
    success_url = reverse_lazy('empleados:empleados_list')

    def get_context_data(self, **kwargs):
        context = super(EmpleadosUpdate, self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class(self.request.GET)
        if 'form2' not in context:
            id_direccion=kwargs['form'].initial.get('direccion',0)
            try:
                direccion = Direccion.objects.get(id=id_direccion)
            except Direccion.DoesNotExist:
                pass
            form2 = self.second_form_class(instance=direccion)
            context['form2'] = form2
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        id_empleado = kwargs['pk']
        empleado = self.model.objects.get(id=id_empleado)
        form = self.form_class(request.POST,instance=empleado)
        id_direccion = self.request.POST.get('direccion')
        direccion = Direccion.objects.get(id=id_direccion)
        form2 = self.second_form_class(request.POST,instance=direccion)
        if form.is_valid() and form2.is_valid():
            form.save(commit=False)
            form2.save(commit=False)
            #usuario.direccion = form2.save()
            #usuario.save()
            form.save()
            form2.save()
            return HttpResponseRedirect(self.get_success_url())
        else    :
            return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('empleados:empleados_list')


class EmpleadosDelete(DeleteView):
    model = Empleado
    success_url = reverse_lazy('empleados:empleados_list')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.activo=0
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

apps/empleados/templates/empleados/empleado_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<body>
<div class="container">
    <div class="row">
        <h1>¿Desea eliminar el registro?</h1>
    </div>
    <div class="row">
           <form method="post">{% csrf_token %}
       <table class="table table-hover table-bordered" >
            <thead>
                <tr>
                    <td class="info"><strong>ID</strong> </td>
                    <td class="info"> <strong class="text-center">Nombre</strong> </td>
                    <td class="info"> <strong>Apellido Paterno</strong> </td>
                    <td class="info"> <strong>Apellido Materno</strong> </td>
                    <td class="info"> <strong>Fecha de Nacimiento</strong> </td>
                    <td class="info"> <strong>CURP</strong> </td>
                    <td class="info"> <strong>RFC</strong> </td>
                    <td class="info"><strong> Dirección</strong> </td>


                </tr>
            </thead>
      <tbody>

            <tr>
                <td> {{ empleado.id }}</td>
                <td> {{ empleado.nombre }} </td>
                <td> {{ empleado.apellido_paterno }} </td>
                <td> {{ empleado.apellido_materno }} </td>
                <td> {{ empleado.fecha_nacimiento|date:"Y-m-d" }} </td>
                <td> {{ empleado.curp }} </td>
                <td> {{ empleado.rfc }} </td>

                <td>
                    {{ empleado.direccion.get_full_information|truncatechars:30 }}
                </td>


        </tr>

      </tbody>

        </table>


    <input type="submit" value="Aceptar" class="btn btn-primary"/>
        <a href="/empleados/" class="btn btn-default" >Cancelar</a>
    </form>
    </div>

</div>

</body>
{% endblock %}

apps/empleados/templates/empleados/empleado_form.html
{% extends 'base.html' %}
{% block content %}
<body>
    <div class="container">
        <div class="row">
             <h1 class="text-center titulo-registrarse">Registro de Empleado</h1><br><br>
        </div>
        <div class="row">
             <div class="col-md-4">

             </div>
             <div class="col-md-4">

                 <form class="form-horizontal" id="formulario" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    {{ form2.as_p }}
                     <div class="form-group">
                         <br><br>
                         <input type="submit" value="Guardar" class="btn btn-primary espacio-boton">
                         <a href="/empleados/" class="btn btn-default espacio-boton" >Cancelar</a>
                     </div>


                 </form>

             </div>
             <div class="col-md-4">
             </div>
         </div>

    </div>


    <div class="row">
        <p></p>
    </div>

</body>
{% endblock %}

apps/empleados/templates/empleados/empleado_list.html
{% extends 'base.html' %}
{% block content %}
<body>

    <div class="container">
        <h1>Empleados</h1>
        <div>
             <a href="{% url 'home' %}" class="btn btn-default" ><span class="glyphicon glyphicon-home"></span> Inicio</a>
             <a href="{% url 'empleados:empleados_new' %}" class="btn btn-success"><span class="glyphicon glyphicon-file"></span> Nuevo registro de empleados</a><br><br>
        </div>
        <table class="table table-hover table-bordered" >
            <thead>
                <tr>
                    <td class="info"><strong>ID</strong> </td>
                    <td class="info"> <strong class="text-center">Nombre</strong> </td>
                    <td class="info"> <strong>Apellido Paterno</strong> </td>
                    <td class="info"> <strong>Apellido Materno</strong> </td>
                    <td class="info"> <strong>Fecha de Nacimiento</strong> </td>
                    <td class="info"> <strong>CURP</strong> </td>
                    <td class="info"> <strong>RFC</strong> </td>
                    <td class="info"><strong> Dirección</strong> </td>
                    <td class="info"><strong>Actualizar</strong> </td>
                    <td class="info"> <strong>Eliminar</strong> </a></td>
                </tr>
            </thead>
      <tbody>
            {% for empleado in object_list %}
            <tr>
                <td> {{ empleado.id }}</td>
                <td> {{ empleado.nombre }} </td>
                <td> {{ empleado.apellido_paterno }} </td>
                <td> {{ empleado.apellido_materno }} </td>
                <td> {{ empleado.fecha_nacimiento|date:"Y-m-d" }} </td>
                <td> {{ empleado.curp }} </td>
                <td> {{ empleado.rfc }} </td>

                <td>
                    {{ empleado.direccion.get_full_information|truncatechars:30 }}
                </td>

                <td> <a href="{% url 'empleados:empleados_edit' empleado.id %}" class="btn btn-default"><span class="glyphicon glyphicon-refresh"></span></a></td>
                <td> <a href="{% url 'empleados:empleados_delete' empleado.id %}" class="btn btn-default"><span class="glyphicon glyphicon-remove"></span></a></td>
        </tr>
        {% endfor %}
      </tbody>

        </table>

    <div class="footer">

    </div>
    </div>

</body>
{% endblock %}